### ISSUE TITLE
Interested in collaborating and contributing

### ISSUE THREAD

**Issue by jramirez857** [justmedude/pylotoncycle#13]
Hello, 

I have recently been working on a dashboard for my peloton workouts using csv format output from my peloton account. However, I am interested in extending it to be able to use the api using pylotoncycle. Would you be interested in collaborating on this project?

Either way, I look forward to hearing your thoughts!

**Comment by justmedude** [comment]
What do you have in mind?
I otherwise pull in my data to a local database and then use [grafana](https://grafana.com/) to create a dashboard. You can see the example code in the [examples](https://github.com/justmedude/pylotoncycle/tree/master/examples) directory

**Comment by jramirez857** [comment]
Interesting, thanks for pointing me to Grafana. I will look into it and compare it to [Dash](https://dash.plotly.com/) which is what I've been using to create my dashboards.

I have been considering doing the same with Strava data since that is what I use for keeping track of my workouts (peloton and non peloton workouts). I want to eventually be able to deploy a full featured dashboard which users can log into to gain insights on their workout data (streaks, trends, badges and accomplishments etc). I see you have a lot of scripts related to workout data so maybe we share some of the same motivations 😂😂. Does any of this interest you?

**Comment by justmedude** [comment]
Definitely of interest, but being completely honest, I don't have a lot of free time these days for some of these side projects. I'll certainly be interested in seeing what you come up with, though.

**Comment by jramirez857** [comment]
That is fine and I'd be interested in at least contributing what I can to this project. Should I open up issues for features I might need for this repo? Since it seems like you are using it elsewhere I would like to be mindful that I don't break your use cases.

**Comment by justmedude** [comment]
Sure, you can open up feature requests, and you can also submit pull requests for adding in features. I would like to keep the requirements for the module be fairly lightweight. As an example, the only additional module required is `requests` which is a very widely used python module.

No promises, but I'll certainly evaluate incoming requests.

**Comment by jramirez857** [comment]
Great, thank you Vikram. I will keep that requirement in mind for any features I need. I understand life happens and do not expect fast turnaround for a hobbyist project either. I look forward to contributing!

**Comment by justmedude** [comment]
Awesome, looking forward to it!

**Comment by simon-tarr** [comment]
Hey @jramirez857, apologies for commenting on a closed issue, hope you see this.

I've been working on a Django-based 'Advanced Peloton Dashboard', I can share a link in a few weeks when it's deployed, if you like? I've been using this repository as reference, tweaking and modifying some code to make it work better in Django (mostly I modified the function `GetWorkoutList` as I'd already written my own code for logging in)

The thing I'm currently thinking about is how to work through the list of `workout_id`'s to grab the more detailed workout metrics (cadence, average speed etc.). It takes between 0.5-1s here to grab data from the workout endpoint at https://api.onepeloton.com/api/workout/<workout_id>/performance_graph/.

I'm a little concerned about Peloton rate limiting all the calls, especially if users to my application have many 1000s of workouts (which I suspect they will). The benefit of using a database driven app is that the 1000s of calls only have to happen once - once I've saved them, I only grab new workouts since the last sync.

Anyway, if you or anyone else has any ideas of how to reduce the number of calls to the API, I'm all ears (but I suspect I may not be able to make things any more efficient)

Cheers!

**Comment by Rafatpanah** [comment]
The way the current Peloton API works, it is pretty inefficient and you have to make a separate API call for each workout that you want to get the details on. I haven't figured out a way to batch the requests, but it might be possible.
I have a similar project that I am doing to learn ([peloduel.com](url)) and make parallel async requests for every user for each workout (~100-500 simultaneous requests) and it usually takes ~2-4 seconds for all the requests to resolve and process the page.
The one thing to be aware of when storing items in a database is that technically a user can delete an existing workout. Therefore you would still need to grab the user's workout list and compare workout ids to mark any deleted ones as inactive.

**Comment by simon-tarr** [comment]
Hey @Rafatpanah thanks for joining the discussion :)

Yes, the API is a pain (but I'm grateful one exists). My original plan--when I first learned there even was an API I could tap into--was to have only a small DB in my app, holding things like user-specified goals and targets for the month. I would grab the data for graphs etc. with direct API calls to Peloton on page render. After playing around and realising that I was coding in a straight jacket due to inefficient endpoints, I decided to essentially sync my data to my own postgres DB in Django, then build my own API from that using Django REST framework. The long way round...

You make a good point about deleted workouts, I hadn't actually considered this. It should be reasonably easy to get around though; compare the list of workout IDs I have in my DB with the list of workout IDs generated with a call to `/api/user/user_id/workouts`. Anything that's missing in the latter list has (presumably) been deleted and I can flag it as such in my app (and offer the user to delete or keep as an archive.)

What's a hobby project if it's not building an entire REST API on top of an undocumented and 'unofficial' API which is subject to change/withdrawl at any minute?! 🧐

**Comment by simon-tarr** [comment]
For sure, it's nice to hear what others are up to :) Thanks @justmedude for your work with this repo - I've found it a mightily useful reference as I stumble through creating my app.

I haven't got around to coding workout deletion yet but I was thinking of tacking it onto the end of the user-triggered 'Re-Sync' workout Celery task I have. Example workflow:

1. Ping `https://api.onepeloton.com/api/user/user_id/overview'` and grab list of workout IDs, save basic workout data to app's `WorkoutData` model if a record doesn't already exist.
2. Loop through all `workout_id`'s in `WorkoutData`. Grab detailed workout data for each workout and save to appropriate model (e.g. `CyclingData` and `YogaData`). Skip this if the record already exists.
3. Compare list of Workout IDs from API call in Step 1 to all `workout_id`'s in `WorkoutData`, flag if potentially deleted.

I'll perhaps limit the app to only allow 3-4 syncs a day to as to not spam the API.

**Comment by justmedude** [comment]
Ok, so a manual re-sync is what would trigger the deletion process, which makes sense.
For doing your re-sync logic, you could store something like "last re-sync", and if it's under X amount of time, then you disallow it. This gives you an easy method of limiting the number per day without having to track the actual number.

**Comment by Rafatpanah** [comment]
I'd love to check out your product when it is ready to demo!
My end goal is to use IndexedDB to store the user's data (similar to your process) but have the refresh occur asynchronously on the page load and update the page when done.
The one thing that I can add that I haven't found in other places is you should consider using the endpoint `https://api.onepeloton.com/api/user/${user_id}/workouts?joins=ride` instead of `https://api.onepeloton.com/api/user/${user_id}/workouts`. This will also return information on specific workout (like ride id) that is useful if you want to display information on the specific workout or you want to find what friends have taken the same ride.

**Comment by simon-tarr** [comment]
> Ok, so a manual re-sync is what would trigger the deletion process, which makes sense.
> For doing your re-sync logic, you could store something like "last re-sync", and if it's under X amount of time, then you disallow it. This gives you an easy method of limiting the number per day without having to track the actual number.

Good idea! I have a 'last_sync' field in my `WorkoutData` model which is populated every time a user syncs (initial or re-syncs) so it'll be trivial to implement the code like you suggest.
